[package]
name = "bassietest"
version = "0.1.0"
edition = "2021"

[dependencies]
objc = { git = "https://github.com/bplaat/crates.git" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
opt-level = "z"
panic = "abort"
lto = "fat"
